apiVersion: v1
kind: Service
metadata:
  name: integration-app-service
spec:
  selector:
    app: integration-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
