name: CI/CD - Build, Push & Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: v1-${{ github.run_number }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push index service
      uses: docker/build-push-action@v5
      with:
        context: ./random-num-gen-service
        push: true
        tags: |
          welkinoid/index:${{ env.VERSION }}

    - name: Build & push client service
      uses: docker/build-push-action@v5
      with:
        context: ./integration-app
        push: true
        tags: |
          welkinoid/client-service:${{ env.VERSION }}

    - name: Update Kubernetes manifests with new image tags
      run: |
        sed -i "s|welkinoid/index:.*|welkinoid/index:${VERSION}|" ./k8s/random-num-gen-deployment.yaml
        sed -i "s|welkinoid/client-service:.*|welkinoid/client-service:${VERSION}|" ./k8s/integration-app-deployment.yaml

    - name: Commit and push updated manifests
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        git add ./k8s/*.yaml
        git commit -m "CI: update image tags to ${VERSION}" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref_name }}
