name: CI- Build and Push Microservices

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push index service
      uses: docker/build-push-action@v5
      with:
        context: ./random-num-gen-service
        push: true
        tags: |
          welkinoid/index:${{ github.event.inputs.version }}

    - name: Build & push clientService
      uses: docker/build-push-action@v5
      with:
        context: ./integration-app
        push: true
        tags: |
          welkinoid/client-service:${{ github.event.inputs.version }}
